name: Greetings

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v3
        with:
          issue-message: "Thanks for opening your first issue. Pull requests are always welcome too! :)"
          pr-message: "Thank you for your contribution. We will be reviewing your PR shortly! In the meantime, please make sure all status checks have passed."
