name: Tag and Publish Release

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "*.txt"
      - "*.md"

jobs:
  prepare-github-release:
    permissions:
      contents: write
    name: GitHub Release
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.calculate_tag_version.outputs.version_tag }}
    steps:

      - name: Checkout project sources
        uses: actions/checkout@v4
        # https://github.com/marketplace/actions/git-semantic-version#important-note-regarding-the-checkout-action
        with:
          fetch-depth: 0

      - name: Manage semantic versioning
        uses: paulhatch/semantic-version@v5.4.0
        id: semantic_version
        with:
          tag_prefix: ""
          major_pattern: "[MAJOR]"
          minor_pattern: "[MINOR]"
          bump_each_commit: true
          bump_each_commit_patch_pattern: "[PATCH]"
          version_format: "${major}.${minor}.${patch}"
          search_commit_body: true
          debug: true

      - name: Bump the version and push a tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.semantic_version.outputs.version_tag }}
          tag_prefix: ""

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1.16.0
        with:
          tag: ${{ steps.semantic_version.outputs.version_tag }}
          name: ${{ steps.semantic_version.outputs.version_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          makeLatest: true
          generateReleaseNotes: true
          skipIfReleaseExists: true

